---
- name: create configuration directory
  sudo: yes
  file:
    path: /etc/logstash.d
    state: directory
    mode: 0755
  tags:
    - logstash

- name: configure logstash
  sudo: yes
  template:
    src: logstash.conf.j2
    dest: /etc/logstash.d/logstash.conf
  notify:
    - restart logstash
  tags:
    - logstash

- name: generate systemd service file
  sudo: yes
  template:
    src: logstash-service.j2
    dest: /usr/lib/systemd/system/logstash.service
  notify:
    - reload systemd daemon
    - enable and start logstash
  tags:
    - logstash

- name: forward all logs from rsyslog to logstash
  sudo: yes
  lineinfile:
    dest: /etc/rsyslog.conf
    line: '*.* @@localhost:1514'
  notify:
    - restart rsyslog
  tags:
    - logstash

- meta: flush_handlers
