---
- name: create json files for jobs
  sudo: yes
  template:
    src: '{{ item }}.json.j2'
    dest: /etc/marathon/{{ item }}.json
  with_items:
    - mesos-consul
    - marathon-consul
  tags:
    - marathon

- name: start jobs
  run_once: true
  sudo: yes
  command: 'curl -X PUT -d@/etc/marathon/{{ item }}.json -H "Content-Type: application/json" http://localhost:18080/v2/apps/{{ item }}'
  changed_when: false
  with_items:
    - mesos-consul
    - marathon-consul
  tags:
    - marathon

- name: set event hooks
  run_once: true
  command: 'curl -X POST http://localhost:18080/v2/eventSubscriptions?callbackUrl={{ item }}'
  changed_when: false
  with_items:
    - http://marathon-consul.service.consul:4000/events