---
- hosts: all
  roles:
    - common
    - collectd
    - logrotate
    - consul-template
    - docker
    - dnsmasq
    - nginx
    - consul
    - logstash
    - vault
    - zookeeper
    - mesos
    - marathon
