---
- name: copy nginx configuration
  sudo: yes
  template:
    src: mesos-leader.nginx.j2
    dest: /etc/mesos-leader.nginx
  tags:
    - mesos

- name: configure nginx
  sudo: yes
  command: curl -X PUT -d @/etc/mesos-leader.nginx localhost:8500/v1/kv/service/nginx/templates/mesos-leader
  tags:
    - mesos

- name: configure nginx-mesos-leader
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-mesos-leader.service.j2
      dest: /usr/lib/systemd/system/nginx-mesos-leader.service
    - src: nginx-mesos-leader.env.j2
      dest: /etc/default/nginx-mesos-leader.env
  tags:
    - mesos
  tags:
    - reload nginx-mesos-leader
    - restart nginx-mesos-leader

- name: enable nginx-mesos-leader
  sudo: yes
  service:
    name: nginx-mesos-leader
    enabled: yes
    state: started
  notify:
    - restart nginx-mesos-leader
  tags:
    - mesos
